### ISSUE TITLE
Mentions Not working for Qanda Plugin

### ISSUE THREAD

**Issue by ArijitBanerjee** [rdumitriu/jira-qanda#15]
Mentions Not working for Qanda Plugin.What can be the probable reason?

**Comment by ArijitBanerjee** [comment]
Log shows:

 /rest/agrade/qanda/latest/mentions/search [common.error.jersey.ThrowableExceptionMapper] Uncaught exception thrown by REST service: com.atlassian.jira.rest.v2.issue.UserBeanBuilder.<init>(Lcom/atlassian/jira/issue/fields/rest/json/beans/JiraBaseUrls;)V
java.lang.NoSuchMethodError: com.atlassian.jira.rest.v2.issue.UserBeanBuilder.<init>(Lcom/atlassian/jira/issue/fields/rest/json/beans/JiraBaseUrls;)V
        at ro.agrade.jira.qanda.rest.QandAMentionsRestService.makeUserBeans(QandAMentionsRestService.java:162)
        at ro.agrade.jira.qanda.rest.QandAMentionsRestService.getAutocomplete(QandAMentionsRestService.java:129)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

**Comment by rdumitriu** [comment]
On which JIRA? Could you pls tell me the JIRA version you're using?

**Comment by ArijitBanerjee** [comment]
JIRA 6.4

**Comment by rdumitriu** [comment]
Ah, ah. Yet another change. I will fix it in the week-end.

**Comment by ArijitBanerjee** [comment]
Is the issue resolved?

**Comment by rdumitriu** [comment]
Nope. I tried to reproduce it on JIRA 6.4.0 , 6.4.5 and 6.4.7. The method is there, and it gets correctly called. May I have the rest of the exception? From your initial description, the root cause of this is hidden. Maybe it's something else ...

**Comment by ArijitBanerjee** [comment]
/rest/agrade/qanda/latest/mentions/search [common.error.jersey.ThrowableExceptionMapper] Uncaught exception thrown by REST service: com.atlassian.jira.rest.v2.issue.UserBeanBuilder.<init>(Lcom/atlassian/jira/issue/fields/rest/json/beans/JiraBaseUrls;)V
java.lang.NoSuchMethodError: com.atlassian.jira.rest.v2.issue.UserBeanBuilder.<init>(Lcom/atlassian/jira/issue/fields/rest/json/beans/JiraBaseUrls;)V
        at ro.agrade.jira.qanda.rest.QandAMentionsRestService.makeUserBeans(QandAMentionsRestService.java:162)
        at ro.agrade.jira.qanda.rest.QandAMentionsRestService.getAutocomplete(QandAMentionsRestService.java:129)
        at sun.reflect.GeneratedMethodAccessor3452.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)  <+19> (DispatchProviderHelper.java:234) (DispatchProviderHelper.java:100) (DefaultMethodInvocation.java:61) (ExpandInterceptor.java:38) (DefaultMethodInvocation.java:61) (DispatchProviderHelper.java:132) (DispatchProviderHelper.java:230) (ResourceJavaMethodDispatcher.java:75) (HttpMethodRule.java:288) (RightHandPathRule.java:147) (ResourceClassRule.java:108) (RightHandPathRule.java:147) (RootResourceClassesRule.java:84) (WebApplicationImpl.java:1469) (WebApplicationImpl.java:1400) (WebApplicationImpl.java:1349) (WebApplicationImpl.java:1339) (WebComponent.java:416) (ServletContainer.java:537)
        at com.atlassian.plugins.rest.module.RestDelegatingServletFilter$JerseyOsgiServletContainer.doFilter(RestDelegatingServletFilter.java:178)  <+1> (ServletContainer.java:795)
        at com.atlassian.plugins.rest.module.RestDelegatingServletFilter.doFilter(RestDelegatingServletFilter.java:73)  <+16> (DelegatingPluginFilter.java:78) (IteratingFilterChain.java:42) (ServletFilterModuleContainerFilter.java:77) (ServletFilterModuleContainerFilter.java:63) (DelegatingPluginFilter.java:78) (IteratingFilterChain.java:42) (DelegatingPluginFilter.java:70) (RestServletUtilsUpdaterFilter.java:26) (RestServletUtilsUpdaterFilter.java:40) (DelegatingPluginFilter.java:78) (IteratingFilterChain.java:42) (DelegatingPluginFilter.java:70) (ContextFilter.java:25) (DelegatingPluginFilter.java:78) (IteratingFilterChain.java:42) (DelegatingPluginFilter.java:70)
        at com.atlassian.mywork.client.filter.ServingRequestsFilter.doFilter(ServingRequestsFilter.java:37)  <+3> (DelegatingPluginFilter.java:78) (IteratingFilterChain.java:42) (DelegatingPluginFilter.java:70)
        at com.atlassian.plugins.cors.CorsFilter.doFilter(CorsFilter.java:65)  <+3> (DelegatingPluginFilter.java:78) (IteratingFilterChain.java:42) (DelegatingPluginFilter.java:70)
        at com.atlassian.prettyurls.filter.PrettyUrlsSiteMeshFixupFilter.doFilter(PrettyUrlsSiteMeshFixupFilter.java:36)  <+3> (DelegatingPluginFilter.java:78) (IteratingFilterChain.java:42) (DelegatingPluginFilter.java:70)
        at com.atlassian.prettyurls.filter.PrettyUrlsDispatcherFilter.doFilter(PrettyUrlsDispatcherFilter.java:60)  <+3> (DelegatingPluginFilter.java:78) (IteratingFilterChain.java:42) (DelegatingPluginFilter.java:70)
        at com.atlassian.prettyurls.filter.PrettyUrlsSiteMeshFilter.doFilter(PrettyUrlsSiteMeshFilter.java:92)  <+3> (DelegatingPluginFilter.java:78) (IteratingFilterChain.java:42) (DelegatingPluginFilter.java:70)
        at com.atlassian.prettyurls.filter.PrettyUrlsMatcherFilter.doFilter(PrettyUrlsMatcherFilter.java:56)  <+3> (DelegatingPluginFilter.java:78) (IteratingFilterChain.java:42) (DelegatingPluginFilter.java:70)
        at com.atlassian.labs.botkiller.BotKillerFilter.doFilter(BotKillerFilter.java:36)  <+21> (DelegatingPluginFilter.java:78) (IteratingFilterChain.java:42) (ServletFilterModuleContainerFilter.java:77) (ServletFilterModuleContainerFilter.java:63) (ApplicationFilterChain.java:241) (ApplicationFilterChain.java:208) (AccessLogFilter.java:107) (AccessLogFilter.java:91) (ApplicationFilterChain.java:241) (ApplicationFilterChain.java:208) (XsrfTokenAdditionRequestFilter.java:54) (ApplicationFilterChain.java:241) (ApplicationFilterChain.java:208) (PageBuilderFilter.java:90) (ApplicationFilterChain.java:241) (ApplicationFilterChain.java:208) (CommittedResponseHtmlErrorRecoveryFilter.java:63) (ApplicationFilterChain.java:241) (ApplicationFilterChain.java:208) (IteratingFilterChain.java:46) (DelegatingPluginFilter.java:70)
        at com.atlassian.prettyurls.filter.PrettyUrlsCombinedMatchDispatcherFilter.doFilter(PrettyUrlsCombinedMatchDispatcherFilter.java:61)  <+22> (DelegatingPluginFilter.java:78) (IteratingFilterChain.java:42) (ServletFilterModuleContainerFilter.java:77) (ServletFilterModuleContainerFilter.java:63) (ApplicationFilterChain.java:241) (ApplicationFilterChain.java:208) (SecurityFilter.java:239) (ApplicationFilterChain.java:241) (ApplicationFilterChain.java:208) (TrustedApplicationsFilter.java:100) (ApplicationFilterChain.java:241) (ApplicationFilterChain.java:208) (BaseLoginFilter.java:172) (JiraLoginFilter.java:70) (ApplicationFilterChain.java:241) (ApplicationFilterChain.java:208) (IteratingFilterChain.java:46) (DelegatingPluginFilter.java:70) (OAuthFilter.java:79) (DelegatingPluginFilter.java:78) (IteratingFilterChain.java:42) (DelegatingPluginFilter.java:70)
        at com.atlassian.plugins.rest.module.servlet.RestSeraphFilter.doFilter(RestSeraphFilter.java:40)  <+3> (DelegatingPluginFilter.java:78) (IteratingFilterChain.java:42) (DelegatingPluginFilter.java:70)

**Comment by rdumitriu** [comment]
ok, found the problem. Expect a fix soon.

**Comment by ArijitBanerjee** [comment]
By when can we expect the issue to be fixed?

**Comment by sonic1200** [comment]
I have the same issue on my JIRA 6.4.12 currently.
Can we expect a fix for JIRA 6.4.x of this plugin?
I found this plugin very interesting and add great value for our internal communications, so I don't want to remove it since I have upgraded my JIRA :-)
